// src/data/projectsData.js

export const projectsData = [
  // =========================================================================
  // Project 1: Remnants of Love (Original Data Preserved)
  // =========================================================================
  {
    "id": 1,
    "title": "Remnants of Love",
    "category": "AI-Native Game / Technical Art Research",
    "date": "August 2025",
    "content": [
      {
        "type": "text",
        "value": "**Exploring Non-Deterministic Interaction and AI-Native Pipelines via Large Language Models**"
      },
      {
        "type": "text",
        "value": "### 1. Project Overview\n\n**Remnants of Love** is an AI-native anime romance simulation game designed to reconstruct traditional game interaction logic and narrative experiences using Large Language Models (LLMs).\n\n* **World Setting:** The game is set in a Victorian-era England perpetually shrouded in night and steam—a nightmare world resembling \"Foggy London.\"\n* **Core Narrative:** Players assume the role of the protagonist, \"Cheng,\" who is trapped in this realm. To escape the time loop, he must win back the affection of three ex-girlfriends with distinct personalities through actions and dialogue.\n* **Project Vision:** Beyond gameplay, this project aims to address common technical challenges in LLM game integration—such as \"hallucinations,\" \"OOC (Out of Character)\" behavior, and \"sycophantic\" responses—while exploring the boundaries of **Non-Deterministic Interaction** in gaming."
      },
      {
        type: "youtube",
        videoId: "yjyoXjUFatU",
        caption: "Promotional Video (PV): This video is AI-generated."
      },
      {
        type: "youtube",
        videoId: "EVNUL4buzpA",
        caption: "Opening: This video is AI-generated."
      },
      {
        "type": "text",
        "value": "### 2. Core Gameplay: Dual-Loop Mechanism\n\nThe game utilizes a **\"Micro-Interaction\" (Inner Loop) and \"Macro-Exploration\" (Outer Loop)** structure, where both loops are intrinsically linked to create an immersive experience.\n\n**2.1 Inner Loop: Strategic Non-Linear Interaction**\nThis is the core cycle. Players must devise strategies based on the three heroines' contrasting personalities (e.g., Gentle, Cold/Controlling, Yandere) to increase affinity.\n\n* **Actions:** Players can execute commands like \"Hold Hands,\" \"Pat Head,\" or \"Hug.\" Unlike fixed animations in traditional games, the heroine's reaction and dialogue are generated in real-time by the LLM based on her current \"Affinity\" and \"Emotional State.\"\n* **Gifting:** An inventory system for giving items. Preferences vary significantly (e.g., one loves sweets, another hates the smell of chocolate); giving the wrong gift triggers negative feedback, adding strategic depth.\n* **Dialogue (The Innovative \"Attitude\" System):** We replaced traditional fixed dialogue trees with an \"Attitude\" selection (e.g., \"Make an invitation\" or \"Gently comfort her\"), where the specific lines are generated by AI. It also supports **Free Input**, allowing players to type anything for a truly open-ended conversation."
      },
      {
        type: "image-group",
        images: [
          "/inner-loop.gif",
          "/inner-loop2.gif",
          "/inner-reaction.jpeg",
        ],
        caption: "As demonstrated, the heroine responds instantly to specific player actions. This triggers a dual-layer feedback system: a context-aware reaction generated by the LLM, and a quantitative update to the Affinity Value based on the semantic scoring of the interaction."
      },

      {
        "type": "text",
        "value": "**2.2 Outer Loop: 3D Map Exploration & Narrative Supplement**\n\n* **Exploration Mechanism:** Players control a 3D avatar of the protagonist (generated by AI and rigged with skeletons) to freely navigate the Victorian-styled map.\n* **Resource & Information Collection:** Players explore locations like cafes and fortune-telling shops to collect chests (containing gold, roses, etc.) and converse with NPCs. This allows them to gather key clues regarding the heroines' backgrounds, preferences, and hidden storylines to assist in the inner loop strategy."
      },
      {
        type: "image-group",
        images: [
          "/map.gif",
          "/npc.gif",
          "/gift.png"
        ],
        caption: "As shown, players traverse the Victorian landscape to locate chests and converse with NPCs. In this example, the player pays a gold coin to a witch in the divination shop to uncover hidden information regarding the heroine."
      },
      {
        "type": "text",
        "value": "### 3. System Architecture: Engineering Solutions for LLM Integration\n\n**The Challenge: \"Hallucination\" vs. \"Game Design\"**\nIntegrating Large Language Models into core gameplay faces three critical hurdles:\n1. **Uncontrollability:** LLMs often \"hallucinate\" or break character logic.\n2. **Sycophancy:** The AI tends to act as a \"Yes-man,\" blindly agreeing with the player and removing all gameplay challenges.\n3. **Weak Feedback:** Pure text responses lack the visceral impact and clear objectives of traditional games.\n\nTo address these, we designed a hybrid architecture that constrains the generative AI within strict game rules:\n\n**3.1 Solution: Dynamic Emotion State Machine**\nTo solve the issue of **Unpredictable Behavior**, we introduced **Emotion** as a deterministic variable. The LLM cannot simply \"choose\" how to react; it must follow a rigid state machine (Joy, Anger, Shyness, Boredom). This ensures logical consistency—for example, a \"Hug\" action that succeeds in a **Joy** state will trigger a rejection in an **Angry** state. This structure forces the player to strategize rather than randomly input text.\n\n**3.2 Solution: Separated Scoring & RAG**\n* **Combating Sycophancy (Separated Scoring):** LLMs struggle with numerical balance. We decoupled the logic: the LLM acts only as a **Semantic Judge** (rating input suitability on a 1-5 scale), while the **Game Engine** handles the actual Affinity calculation. This prevents the AI from arbitrarily inflating scores just to please the player.\n* **Combating Memory Loss (RAG & Context):** Standard context windows are limited. We implemented a **Retrieval-Augmented Generation (RAG)** system that injects specific \"Character Bio\" fragments only when relevant clues are triggered, ensuring the heroine remembers long-term plot points without context overflow.\n* **Combating Weak Feedback (AV Enhancement):** Text alone is boring. The system maps semantic outcomes to **AI-generated visual expressions** and screen effects, converting abstract text into tangible, high-impact gameplay feedback."
      },
      {
        "type": "card-gallery",
        "items": [
          {
            "src": "/girl1.png",
            "title": "Misokazuki",
            "desc": "A Chunibyo girl who believes she is a witch of dark magic and regards the player as her bound knight."
          },
          {
            "src": "/girl2.png",
            "title": "Tsugomori",
            "desc": "A Yandere character with obsessive dependency and a suffocating desire to control the player's interactions."
          },
          {
            "src": "/girl3.png",
            "title": "Mochizuki",
            "desc": "Seemingly gentle but secretly manipulative (Haraguro); she meticulously studies 'The Standard Beau Catcher' to ensnare the player's heart."
          }
        ]
      },
      {
        "type": "text",
        "value": "### 4. Technical Highlights: AI-Native Production Pipeline\n\nThis project achieved a full-link AI production workflow—from concept art, UI icons, and voice acting to 3D models and animations—drastically reducing costs while maintaining stylistic consistency.\n\n**4.1 Automated AI-Assisted 3D Scene Pipeline**\nTo address the high cost of asset production, we built an automated **\"Text-to-3D Scene\"** workflow, achieving a 90% AI generation rate for outdoor architectural assets:\n\n* **Step 1: Text-to-Image:** Using fine-tuned Stable Diffusion models to batch-generate Victorian-style orthographic views.\n* **Step 2: Automated 3D Reconstruction:** Converting 2D images into Base Mesh models using automated scripts for photogrammetry, followed by auto-decimation and UV reconstruction.\n* **Step 3: CV Integration (Breakthrough):** The core innovation of this pipeline. We integrated OpenCV-Python with the **Segment Anything Model (SAM)** to enhance details. The system automatically identifies \"window\" regions in textures, generating emission masks to implement realistic batch \"nighttime lighting\" effects within Unity."
      },
      {
        type: "image",
        src: "/model.png",
        caption: "AI-assisted 3D off-site map generation pipeline using SAM and Stable Diffusion."
      },
      {
        type: "image",
        src: "/lighting.png",
        caption: "This figure illustrates the automated pipeline that utilizes cylindrical unwrapping and the Segment Anything Model (SAM) to generate precise window emission masks for realistic nighttime illumination on 3D architectural assets."
      },
      {
        "type": "text",
        "value": "**4.2 Character & Animation Generation**\n* **Character Models:** In-game character models are generated by AI with automated rigging, supporting real-time player control on the map.\n* **Cinematics:** Ending animations and key narrative performances are produced using video generation models, ensuring visual consistency."
      },
      {
        type: "image",
        src: "/UI.png",
        caption: "The UI features a desaturated ivory base with paper textures, evoking a vintage British aesthetic and cultural depth. Burgundy is used as an accent color to contrast with the muted tones, emphasizing critical information and adding visual hierarchy."
      },
      {
        "type": "text",
        "value": "### 5. Aesthetic & Narrative Design\n\n**Visual Style**\nThe game's palette uses ivory paper tones as a base with burgundy accents. We utilize immersive UI elements like paper textures, envelopes, and newspapers, combined with foggy night rendering, to perfectly recreate the oppressive and mysterious atmosphere of 19th-century London.\n\n**Fragmented Narrative & Plot Twist**\n* **Narrative Structure:** We employ fragmented storytelling, hiding foreshadowing within item descriptions, NPC idle chatter, and environmental details.\n* **The Core Twist:** In subsequent playthroughs, players discover that the three distinct heroines are actually **three split personalities of the same person at different ages**.\n* **The Ending:** The AI-generated ending animation features a woman holding tokens from all three heroines, reuniting with the protagonist in the snow, completing the emotional loop."
      },
      {
        "type": "media-text",
        "src": "/end.gif",
        "value": "**The Finale: An Open Ending**\n\nThe game concludes with an AI-generated cinematic CG. The protagonist encounters the heroine on a street.\n\nIn the scene, she holds three symbolic keepsakes that unite the branching narratives: the **Umbrella** representing Misokazuki (who, believing herself a witch, treated it as her magic wand); the **Teddy Bear** symbolizing Tsugomori (her morbidly obsessed substitute for the protagonist); and the **Scarf** belonging to Mochizuki (a cherished gift from the protagonist)."
      }
    ]
  },

  // =========================================================================
  // Project 2: Nebula Analytics (Original Data Preserved)
  // =========================================================================
  {
    "id": 2,
    "title": "AI Piano Evaluator",
    "category": "Human-AI Interaction / Music Education Technology",
    "date": "February 2026",
    "content": [
      {
        "type": "text",
        "value": "**AI Piano Evaluator: An Interactive Multimodal Feedback System for Piano Education**"
      },
      {
        "type": "text",
        "value": "**Tech Stack:** React.js, FastAPI, Librosa, Dynamic Time Warping (DTW)\n\n**Fields:** Human-AI Interaction (HAI), Music Information Retrieval (MIR), EdTech"
      },
      {
        "type": "image-link",
        "src": "/banner.jpg",
        "link": "https://vickyliu0617-ai-piano-evaluator.hf.space/",
        "caption": "Click to try the live demo on Hugging Face."
      },
      {
        "type": "text",
        "value": "### 1. Project Abstract\n\nIn traditional solo piano practice scenarios, beginners often face the dual dilemma of \"inability to distinguish errors\" and \"delayed feedback.\" This project developed a Web-based piano practice evaluation system designed to solve this pain point through **Visual Interaction**.\n\nThe system utilizes **FastAPI** as the backend core, combined with **Librosa** for audio signal processing; the frontend uses **React** to build a high-contrast, gamified interactive interface. By combining **Weighted Dynamic Time Warping (Weighted DTW)** with **Chroma Features**, the system not only accurately identifies pitch accuracy but also pioneers a **Segmented Rhythm Evaluation** by calculating the slope of the time-warping path. Users can visually perceive the differences between their performance (Magenta) and the standard demo (Cyan) in both the time and frequency domains through a dynamic \"Piano Roll.\""
      },
      {
        "type": "github-card",
        "repoName": "vicky-liu17/Piano-Evaluation-Tool",
        "desc": "A full-stack AI system for piano evaluation using Weighted DTW and CQT algorithms, implemented with FastAPI and React.",
        "link": "https://github.com/vicky-liu17/Piano-Evaluation-Tool"
      },
      {
        "type": "text",
        "value": "### 2. Interaction Design & User Experience (UX)\n\nThis system follows the \"Human-Centered AI (HAI)\" design principle, transforming complex audio analysis data into intuitive visual metaphors to reduce the user's cognitive load.\n\n**2.1 Immersive Gamified Interface**\nTo enhance motivation for teenagers and beginners, the UI adopts a **Cyberpunk/Neon style**.\n* **Visual Metaphors:** All interactive elements (buttons, progress bars, waveforms) use high-saturation fluorescent colors (Neon Cyan & Magenta) against a dark background. This mimics the visual experience of \"Rhythm Games,\" transforming tedious practice into a \"level-clearing challenge.\"\n* **Minimalist Workflow:** The interface retains only two core operation areas—\"Standard Sample\" and \"Your Practice\"—supporting file drag-and-drop and instant recording uploads, ensuring zero technical barriers.\n\n**2.2 Hierarchical Feedback Mechanism**\nThe system mimics the feedback logic of a human teacher, providing evaluation from shallow to deep:\n* **Summative Feedback:**\n    * **Intelligent Rating:** The system calculates a comprehensive score based on DTW distance, displaying it as A/B/C ranks.\n    * **Sync Rate:** Utilizing a visual \"Energy Bar\" to display the overall integrity of the performance, providing users with immediate gratification.\n* **Formative Feedback:**\n    * This is the core of the system. Through waveform graphs and piano rolls, it tells the user \"specifically where the mistake is,\" achieving a leap from \"qualitative\" to \"locational\" feedback."
      },
      {
        "type": "image",
        "src": "/piano-UI1.png",
        "caption": "The gamified main interface allows users to upload the standard sample and their practice recording, featuring a high-contrast neon design to enhance user engagement."
      },
      {
        "type": "image",
        "src": "/piano-UI2.png",
        "caption": "The comprehensive analysis dashboard displays the evaluation rank (e.g., A-), sync rate, and a detailed Piano Roll overlay with a rhythm timeline that visualizes tempo stability."
      },
      {
        "type": "text",
        "value": "### 3. Core Functions & Visualization Technology\n\n**3.1 Dynamic Piano Roll Overlay**\nThis is the project's core visualization innovation. Traditional tools often display two audio tracks separately, making comparison difficult. We developed the `PianoRollOverlay` component to implement **Dual-Track Overlay Visualization**:\n\n* **Visual Encoding:**\n    * **Cyan:** Represents the standard demo notes.\n    * **Magenta:** Represents the user's actual performance.\n* **Interaction Logic:**\n    * When the two color blocks overlap completely, they present a mixed color, representing a \"Perfect Performance.\"\n    * When misalignment occurs, users can instantly see if they are \"Rushing\" (Magenta to the left), \"Dragging\" (Magenta to the right), or playing a \"Wrong Note\" (vertical height inconsistency).\n* **Synchronized Playback:** A built-in Playhead synchronizes with the scrolling container, allowing users to click anywhere to jump and repeatedly listen to points of divergence.\n\n**3.2 Intelligent Rhythm Segmentation Analysis**\nBeyond simply telling the user \"you played wrong,\" the system analyzes \"your tempo trends.\"\n\n* **Visual Presentation:** Below the piano roll, the system generates an independent **Rhythm Timeline**:\n    * 🟩 **STEADY (Green):** Rhythm is stable and consistent with the demo.\n    * 🟥 **SLOW (Red):** Performance is significantly slower than the demo.\n    * 🟧 **FAST (Orange):** Performance shows rushing or acceleration.\nThis allows users to judge which phrase in the piece has unstable tempo based on color, without needing music theory knowledge."
      },
      {
        "type": "text",
        "value": "### 4. Algorithmic Implementation\n\nThe backend uses Python (FastAPI) for high-performance computing. The core logic is as follows:\n\n**4.1 Audio Feature Extraction**\nUsing the `Librosa` library to process uploaded MP3/WAV files:\n* **CQT (Constant-Q Transform):** Compared to FFT, CQT has better frequency resolution in the low-frequency range (piano bass), extracting Pitch Class more accurately and aligning better with human auditory perception.\n* **Onset Detection:** Combining Onset Strength Envelope and the YIN algorithm to detect note start points, used to generate discrete note blocks for the piano roll.\n\n**4.2 DTW-Based Rhythm Analysis Algorithm**\nTo achieve automatic \"Fast/Slow/Steady\" judgment, we designed an analysis algorithm based on **DTW Path Slope**:\n\n1. **Path Calculation:** Calculate the Weighted DTW Warping Path between the demo audio and practice audio.\n2. **Slope Differentiation:** The slope of the path represents the local tempo ratio.\n    * Slope ≈ 1: Tempo matches.\n    * Slope > 1: User is playing too fast (timeline compressed).\n    * Slope < 1: User is playing too slow (timeline stretched).\n3. **Gaussian Smoothing & Segmentation:** The slope is denoised using Gaussian filtering, then thresholds are set to slice the performance into different status segments. Short fluctuations are automatically filtered out to ensure feedback is targeted at the musical phrase level."
      },
      {
        "type": "text",
        "value": "### 5. Performance Evaluation & Limitations\n\nBased on the MAPS dataset and real recording tests, we quantitatively evaluated the system's core algorithms. Experimental results show the system performs excellently in **Beginner to Intermediate** piano education scenarios, though room for improvement remains in specific high-difficulty contexts.\n\n**5.1 Success Case: Simple Etude \"Shufflin' Along\"**\nWe invited three beginners of different levels to record \"Shufflin' Along\" and compared the results with expert evaluations:\n\n* **Student A (Excellent):** Fluid performance, no obvious wrong notes.\n    * **DTW Distance: 0.07**.\n    * **Result:** The system's evaluation was highly consistent with the expert's \"Very Positive\" review, verifying high algorithmic precision in ideal conditions.\n* **Student B (Good):** Performance had slight hesitations, but the melody was basically correct.\n    * **DTW Distance: 0.30**.\n    * **Result:** The system identified rhythmic instability and provided a reasonable downgraded score.\n* **Student C (Average):** Overall tempo was slow, and the recording environment had background noise (human voice interference).\n    * **DTW Distance: 0.26**.\n    * **Result:** Despite interference, the system demonstrated good **Robustness**, accurately identifying the main melody and completing alignment, proving the advantage of CQT features in noise resistance.\n\n**5.2 Limitations & Challenges**\nWhile the system excels with beginner pieces, it encountered bottlenecks when processing high-difficulty compositions.\n\n* **Test Case:** *Flight of the Bumblebee*.\n* **Data Performance:** DTW Distance surged to **3.40**, and the Piano Roll showed significant note loss or adhesion.\n* **Analysis:**\n    1. **Rapid Legato:** When playing speed is extremely fast (e.g., >160 BPM sixteenth notes), the energy envelope changes between notes are minimal, causing the Onset detection algorithm to struggle in distinguishing continuous keystrokes, often misinterpreting multiple notes as a single long note.\n    2. **Harmonic Interference:** Dense notes lead to severe overtone overlap, interfering with pitch recognition accuracy."
      },
      {
        "type": "image",
        "src": "/experiment-piano.png",
        "caption": "DTW alignment results for three students performing 'Shufflin' Along', demonstrating how the calculated distances (0.07, 0.30, 0.26) accurately reflect different proficiency levels and rhythmic stability."
      },
      {
        "type": "text",
        "value": "### 6. Conclusion\n\nAI Piano Evaluator breaks through the singularity of traditional audio analysis tools. Through a **Full-Stack Web Implementation**, it encapsulates complex Music Information Retrieval (MIR) algorithms within a highly attractive interactive interface.\n\nAlthough there is room for improvement in recognition at extreme speeds, for the vast majority of beginners, it provides an **instant, visual, and fault-tolerant** practice companion. This project demonstrates how AI technology can transform auditory \"Right and Wrong\" into visual \"Shape and Color,\" providing new ideas for the digital transformation of art education."
      }
    ]
  },

  // =========================================================================
  // Project 3: Components Demo (新样式展示)
  // =========================================================================
{
  "id": 3,
  "title": "Access Our Community (AOC)",
  "category": "Social Impact Tech / HCI & Web Engineering",
  "date": "March 2019",
  "content": [
    {
      "type": "text",
      "value": "**Digitalizing Justice: A Real-Time Pro Bono Matching Platform**"
    },
    {
      "type": "text",
      "value": "### 1. Project Overview\n\n**Access Our Community (AOC)** is a web-based platform designed to revolutionize how legal professionals connect with pro bono opportunities. It serves as an evolution away from manual, email-based communication, aiming to decrease administrative overhead and increase access to justice for vulnerable communities.\n\n* **The Problem:** The traditional pro bono workflow is plagued by \"Email Spaghetti\"—long, non-real-time email chains that lead to missed opportunities and administrative bottlenecks for lawyers and NGOs alike.\n* **The Ecosystem:** The platform connects three key stakeholders: **NGOs** (Service Providers), **Lawyers** (Volunteers), and **Coordinators** (Admins), creating a unified portal for collaboration.\n* **Global Achievement:** This project participated in the **Global Legal Hackathon 2019**, successfully advancing as a **Global Finalist**, ranking among the top 12 teams worldwide."
    },
    {
      "type": "youtube",
      "videoId": "c768LYh2Xz8",
      "caption": "Project Introduction & User Journey: This video illustrates the \"Lucy, Justin, and Penny\" persona narrative."
    },
    {
      "type": "text",
      "value": "### 2. Core Interaction: The \"Three-Sided\" Market\n\nThe system architecture replaces linear communication with a **Centralized Hub Interaction Model**. The UX is designed around three distinct user journeys that interact seamlessly.\n\n**2.1 The Discovery Loop (For Lawyers)**\nLawyers (like the persona \"Lucy\") no longer need to parse through batch emails. The platform offers a **Real-Time Searchable Database**.\n\n* **Smart Filtering:** Lawyers can filter cases based on \"Interest,\" \"Skills,\" and \"Availability\".\n* **Instant Application:** The system reduces the cognitive load of finding work. A lawyer finds a case, applies, and the status updates instantly, preventing the frustration of applying for already-filled cases.\n\n**2.2 The Management Loop (For NGOs)**\nNGOs (like the persona \"Justin\") act as the \"Quest Givers.\"\n\n* **Screen & Upload:** NGOs screen legal needs and upload them as structured data entries rather than unstructured text in emails.\n* **Network Broadcasting:** Opportunities are shared instantly with their specific network of pro bono lawyers, increasing the \"Capacity\" of these organizations to do high-impact work.\n\n**2.3 The Oversight Loop (For Coordinators)**\nCoordinators (like \"Penny\") manage the firm's resources.\n\n* **Administrative Oversight:** They have a dashboard to approve matches, ensuring no conflict of interest before a lawyer takes a case."
    },
    {
        type: "image",
        src: "/structure.png",
        caption: "The conceptual framework of the AOC platform, illustrating the transformation from systemic friction to data-driven social impact."
      },
    {
      "type": "text",
      "value": "### 3. System Architecture: Solving \"Systemic Friction\"\n\n**The Challenge: Latency & Information Asymmetry**\nPrior to AOC, the workflow was asynchronous. NGOs sent emails → Coordinators reviewed → Forwarded to Lawyers → Lawyers replied. This latency meant clients in need often waited too long.\n\n**3.1 Solution: End-to-End Matching System**\nWe implemented a **Single Portal Architecture**. By centralizing the data:\n\n* **Time Efficiency:** Pro bono lawyers save precious time by eliminating the need to manage email threads.\n* **Timely Access:** The community benefits from faster access to justice because the \"matching\" happens in real-time.\n\n**3.2 Solution: Data-Driven Impact (Analytics)**\nOne of the key technical features is the **Reporting Module**. The system automatically tracks hours and engagement. Users can generate reports to demonstrate their contributions to the community, turning abstract \"goodwill\" into quantifiable metrics."
    },
    {
      "type": "text",
      "value": "### 4. Industry Recognition & Testimonials\n\nThe platform has been validated by high-profile adoption and feedback from government officials and international law firms.\n\n> \"We see much potential and merit in the adoption of technology solutions such as the AOC platform in the provision of pro bono community legal services. By effectively streamlining the process of matching and linking the pro bono lawyers with the service users, the AOC platform will not only enhance public access to legal advice services, but also bring convenience to participating lawyers and service providers.\"\n> — **Nicholas Chan**, Assistant Director of Administration at Chief Secretary for Administration's Office, Government of Hong Kong\n\n> \"As well as coordinating pro bono opportunities...I have a full workload of legal work and other corporate social responsibility initiatives to handle. So we're interested in working with our existing pro bono partners in trialling technology solutions like the AOC platform that can increase efficiency and streamline the process for connecting our lawyers with pro bono opportunities.\"\n> — **Emile McPhee**, Senior Associate and Chair of CCP Committee for pro bono and CSR activities at McCullough Robertson, Brisbane, Australia\n\n> \"Ashurst, like most law firms, do not have a pro bono team based in Asia. For us, our team is based in London and Sydney. This presents capacity, resourcing and time zone issues. We see the AOC platform as helping to fill those needs. AOC will be a much-needed addition to the pro bono environment in Asia.\"\n> — **Sarah Morton-Ramwell**, Partner and Global Head of Pro Bono Practice and Corporate Responsibility Programme at Ashurst, Sydney, Australia\n\n> \"We're proud that Access Our Community is led by one of our own pro bono committee members who has a track record for growing the network of in-house lawyers engaged in pro bono work. AOC will provide a much-needed platform for enabling lawyers to get easily connected and involved with pro bono opportunities.\"\n> — **Lin Shi**, President of Association of Corporate Counsel, Hong Kong\n\n> \"PathFinders is excited about the prospect of having an NGO-to-law firm matching platform.\"\n> — **Celine Dermine**, Access to Justice Programme Manager, PathFinders, Hong Kong"
    }
  ]
},
  {
    id: 4,
    title: "Remnants of Love",
    category: "AI-Native Game / Technical Art Research",
    date: "August 2025",
    content: [
      {
        type: "text",
        value: "**Exploring Non-Deterministic Interaction and AI-Native Pipelines via Large Language Models**\n"
      },
      {
        type: "text",
        value: "### 1. Project Overview\n\nRemnants of Love is a romance simulation game set in a fictional Victorian-era world. Deviating from the pre-scripted \"branching tree\" structures of traditional interactive fiction, our team investigates how Generative AI (AIGC) can reconstruct the game's core loop.\n\nPlayers must navigate a nightmare world, employing strategy and dialogue to conquer a heroine with split personalities. Our project not only validates the potential of Large Language Models (LLMs) in dynamic storytelling but also successfully constructs a deep interaction system based on semantic evaluation."
      },
      {
        type: "youtube",
        videoId: "yjyoXjUFatU",
        caption: "Promotional Video (PV): This video is AI-generated."
      },
      {
        type: "youtube",
        videoId: "EVNUL4buzpA",
        caption: "Opening: This video is AI-generated."
      },
      {
        type: "text",
        value: "### 2. Core Gameplay Loop\n\nWe designed a dual-loop gameplay structure where **Macro-Exploration (The Outer Loop)** and **Micro-Interaction (The Inner Loop)** are intrinsically linked:\n\n* **Macro-Exploration:** Players navigate a 3D open world to gather narrative fragments and NPC-preferred gifts, facilitating long-term information accumulation.\n* **Micro-Interaction:** Players engage directly with the NPC through three core mechanics: Dialogue, Gifting, and Action.\n* **The Synergy:** Exploration provides the necessary context for interaction. A deeper understanding of the character—derived from the outer loop—allows for more informed dialogue choices, significantly accelerating player progression."
      },
      {
        type: "image",
        src: "/outside.png",
        caption: "Macro-Exploration: Navigating the Victorian nightmare world."
      },
      {
        type: "image",
        src: "/emotion.png",
        caption: "Micro-Interaction: Real-time emotional feedback loop."
      },
      {
        type: "text",
        value: "### 3. Core Mechanics: LLM-Driven \"Semantic Gameplay\"\n\nTo address the issues of \"uncontrollability\" and \"lack of objectives\" common in generative AI games, we designed a closed-loop interaction system based on **Semantic Scoring**.\n\n* **Non-Deterministic Dialogue:** Players are no longer confined to fixed dialogue options; instead, they utilize **Open-Ended Input** to interact freely. The LLM acts as a judge, evaluating the **'Semantic Fitness'** of the player's input against the character's persona on a scale of 1 to 5.\n* **State-Driven Emotion System:** We implemented a state machine governed by latent variables (Anger, Boredom, Joy, Shyness). High semantic scores not only increase **Affinity** but also shift her mood toward positive states (e.g., Joy or Shyness), while low scores trigger negative shifts. \n* **Dynamic Interaction Logic:** The NPC's emotional state directly dictates her behavioral logic. For instance, in a **'Joyful'** state, she is more receptive to intimate requests like 'Holding Hands' or 'Hugging'; conversely, in an **'Angry'** state, she will actively reject the same actions, creating a genuine **'Fail State'** based on emotional resonance.\n* **Fragmented Narrative & Long-term Memory:** Leveraging **Prompt Engineering**, key items (e.g., a Teddy Bear) are embedded as **Memory Anchors**. Players must synthesize clues gathered from exploration to navigate the NPC's emotional landscape and guide the conversation effectively."
      },
      {
        type: "image",
        src: "/UI.png",
        caption: "System Architecture: From user input to emotional state transition."
      },
      {
        type: "text",
        value: "### 4. Technical Highlights: AI-Assisted 3D Pipeline\n\nTo address the bottleneck of high asset production costs, we constructed an automated Text-to-3D Scene workflow, achieving 90% AI generation for outdoor architectural assets.\n\n* **Step 1: Text-to-Image:** Using fine-tuned Stable Diffusion models to batch-generate Victorian-style orthographic views.\n* **Step 2: Automated 3D Reconstruction:** Converting 2D images into base mesh models with automated decimation and UV reconstruction scripts.\n* **Step 3: CV Integration (Breakthrough):** We integrated OpenCV-Python with the **Segment Anything Model (SAM)** to enhance details. The system automatically identifies \"window\" regions, generates emission masks, and implements batch \"nighttime lighting\" effects within Unity."
      },

      {
        type: "image",
        src: "/model.png",
        caption: "AI-assisted 3D off-site map generation pipeline using SAM and Stable Diffusion."
      }
    ]
  }
];